/* parser generated by jison 0.4.15 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,8],$V1=[1,16],$V2=[1,9],$V3=[1,10],$V4=[1,11],$V5=[1,12],$V6=[1,13],$V7=[1,14],$V8=[1,15],$V9=[1,10,15,22,23,24,25,26,27,28],$Va=[2,6],$Vb=[1,10,15,20,22,23,24,25,26,27,28],$Vc=[1,20],$Vd=[1,25],$Ve=[1,27],$Vf=[1,28],$Vg=[1,32],$Vh=[13,15,20],$Vi=[1,10,15,19,20,22,23,24,25,26,27,28],$Vj=[13,15];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"program":3,"statements":4,"statement":5,"operation":6,"define":7,"macro":8,"opcode":9,"IDENTIFIER":10,"(":11,"args":12,")":13,"arg":14,",":15,"constant":16,"NUMBER":17,"CHARACTER":18,"=":19,";":20,"stream":21,"+":22,"-":23,"<":24,">":25,"[":26,"]":27,".":28,"$accept":0,"$end":1},
terminals_: {2:"error",10:"IDENTIFIER",11:"(",13:")",15:",",17:"NUMBER",18:"CHARACTER",19:"=",20:";",22:"+",23:"-",24:"<",25:">",26:"[",27:"]",28:"."},
productions_: [0,[3,1],[4,2],[4,1],[5,1],[5,1],[6,1],[6,1],[8,4],[8,3],[12,3],[12,1],[14,1],[14,1],[16,1],[16,1],[7,3],[7,4],[7,4],[21,2],[21,1],[9,1],[9,1],[9,1],[9,1],[9,1],[9,1],[9,1],[9,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
return $$[$0];
break;
case 2: case 19:
this.$ = [$$[$0-1]].concat($$[$0]);
break;
case 3: case 11: case 20:
this.$ = [$$[$0]];
break;
case 4: case 5: case 6: case 12: case 13: case 28:
this.$ = $$[$0];
break;
case 7:
this.$ = ['opcode', $$[$0]];
break;
case 8:
this.$ = ['macro', $$[$0-3], $$[$0-1]];
break;
case 9:
this.$ = ['macro', $$[$0-2], []]
break;
case 10:
this.$ = [$$[$0-2]].concat($$[$0]);
break;
case 14:
this.$ = +$$[$0];
break;
case 15:
this.$ = $$[$0][1]=='\\'?_unescape($$[$0][2]):$$[$0].charCodeAt(1);
break;
case 16:
this.$ = ['define', $$[$0-2], []];
break;
case 17:
this.$ = ['define', $$[$0-3], $$[$0-1]];
break;
case 18:
this.$ = ['set', $$[$0-3], $$[$0-1]];
break;
}
},
table: [{3:1,4:2,5:3,6:4,7:5,8:6,9:7,10:$V0,15:$V1,22:$V2,23:$V3,24:$V4,25:$V5,26:$V6,27:$V7,28:$V8},{1:[3]},{1:[2,1]},{1:[2,3],4:17,5:3,6:4,7:5,8:6,9:7,10:$V0,15:$V1,22:$V2,23:$V3,24:$V4,25:$V5,26:$V6,27:$V7,28:$V8},o($V9,[2,4]),o($V9,[2,5]),o($V9,$Va,{19:[1,18]}),o($Vb,[2,7]),{11:$Vc,19:[1,19]},o($Vb,[2,21]),o($Vb,[2,22]),o($Vb,[2,23]),o($Vb,[2,24]),o($Vb,[2,25]),o($Vb,[2,26]),o($Vb,[2,27]),o($Vb,[2,28]),{1:[2,2]},{6:23,8:24,9:7,10:$Vd,15:$V1,20:[1,21],21:22,22:$V2,23:$V3,24:$V4,25:$V5,26:$V6,27:$V7,28:$V8},{16:26,17:$Ve,18:$Vf},{10:$Vg,12:29,13:[1,30],14:31,16:33,17:$Ve,18:$Vf},o($V9,[2,16]),{20:[1,34]},{6:23,8:24,9:7,10:$Vd,15:$V1,20:[2,20],21:35,22:$V2,23:$V3,24:$V4,25:$V5,26:$V6,27:$V7,28:$V8},o([10,15,20,22,23,24,25,26,27,28],$Va),{11:$Vc},{20:[1,36]},o($Vh,[2,14]),o($Vh,[2,15]),{13:[1,37]},o($Vi,[2,9]),{13:[2,11],15:[1,38]},o($Vj,[2,12]),o($Vj,[2,13]),o($V9,[2,17]),{20:[2,19]},o($V9,[2,18]),o($Vi,[2,8]),{10:$Vg,12:39,14:31,16:33,17:$Ve,18:$Vf},{13:[2,10]}],
defaultActions: {2:[2,1],17:[2,2],35:[2,19],39:[2,10]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        throw new Error(str);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        function lex() {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        }
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

	var _unescape = function _unescape(c){
		switch(c){
			case '0':
				return 0x00;
			case 't':
				return 0x09;
			case 'n':
				return 0x0A;
			case 'r':
				return 0x0D;
			default:
				return c.charCodeAt(0);
		}
	};

function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}